services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - fastapi
      - mongodb

volumes:
  mongo_data:
  grafana_data:

